apiVersion: batch/v1
kind: CronJob
metadata:
  name: notify-applicants-inactive-applications-prod
  namespace: grc-prod
spec:
  schedule: '0 1 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400 #24 hours
      template:
        metadata:
          labels:
            tier: worker
        spec:
          restartPolicy: OnFailure
          serviceAccountName: grc-prod
          containers:
          - name: admin-jobs
            image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/pet/grc-prod-ecr:grc-admin-latest
            imagePullPolicy: Always
            command:
              - /bin/sh
              - -c
              - flask jobs.notify_applicants_inactive_apps run
            envFrom:
              - configMapRef:
                  name: grc-prod-ecr-circleci
            env:
              - name: AWS_REGION
                value: eu-west-2
              - name: BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    name: s3-bucket-output
                    key: bucket_name
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: rds-postgresql-instance-output
                    key: url
              - name: DEFAULT_ADMIN_USER
                value: mark.butler@HMCTS.net
              - name: FLASK_APP
                value: admin
              - name: FLASK_ENV
                value: production
              - name: GOVUK_PAY_API
                value: "https://publicapi.payments.service.gov.uk/"
              - name: GOVUK_PAY_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: basic-auth
                    key: govuk-pay-api-key
              - name: LOG_LEVEL
                value: DEBUG
              - name: MAINTENANCE_MODE
                value: "OFF"
              - name: NOTIFY_API
                valueFrom:
                  secretKeyRef:
                    name: basic-auth
                    key: notifyapi
              - name: NOTIFY_SECURITY_CODE_EMAIL_TEMPLATE_ID
                value: "d93108b9-4a5b-4268-91ee-2bb59686e702"
              - name: NOTIFY_UNFINISHED_APPLICATION_EMAIL_TEMPLATE_ID
                value: "151fce32-1f66-4efd-a875-28026e8d8d70"
              - name: NOTIFY_COMPLETED_APPLICATION_EMAIL_TEMPLATE_ID
                value: "77007bae-b688-4dbb-bc84-334b0f5d3aef"
              - name: NOTIFY_ADMIN_LOGIN_TEMPLATE_ID
                value: "ddfa69ca-e89d-49d1-8311-b487732860ec"
              - name: NOTIFY_ADMIN_FORGOT_PASSWORD_TEMPLATE_ID
                value: "***REMOVED***"
              - name: NOTIFY_ADMIN_NEW_USER_TEMPLATE_ID
                value: "0ff48a4c-601e-4cc1-b6c6-30bac012c259"
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: basic-auth
                    key: csrf
              - name: SQLALCHEMY_DATABASE_URI
                valueFrom:
                  secretKeyRef:
                    name: rds-postgresql-instance-output
                    key: sql_alchemy_url
              - name: SQLALCHEMY_KEY
                valueFrom:
                  secretKeyRef:
                    name: basic-auth
                    key: alchemy-key