jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - run: |
          pytest
