apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
data:
  # username: myuser, ***REMOVED***
  # https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#add-http-basic-authentication
  auth: ***REMOVED***
