"""empty message

Revision ID: 463480f8213b
Revises: 6adf7ebb3032
Create Date: 2025-04-09 08:56:57.107670

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '463480f8213b'
down_revision = '6adf7ebb3032'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('case_registered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('case_registered')
        batch_op.drop_column('case_reference')

    # ### end Alembic commands ###
