FROM bitnamisecure/nginx:latest@sha256:18ca39da7c327a15b5403805d32b3466605ad3683316a6161d31b1250702cd46

COPY index.html /opt/bitnami/nginx/html
COPY conf/maintenance_page.conf /opt/bitnami/nginx/conf/server_blocks/