apiVersion: apps/v1
kind: Deployment
metadata:
  name: grc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grc-app
  template:
    metadata:
      labels:
        app: grc-app
    spec:
      containers:
      - name: grc-app
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/pet/grc-preprod-ecr:grc-app-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: basic-auth
                key: auth
          - name: CONTENT_API_URL
            value: "http://content-api-service:4567/image_url.json"
          - name: FLASK_APP
            value: grc
          - name: SECRET_KEY
            value: <SECRETKEY>
          - name: SQLALCHEMY_DATABASE_URI
            value: "postgresql://postgres:password@localhost:5432/grc"
          - name: SQLALCHEMY_TRACK_MODIFICATION
            value: false
          - name: DEFAULT_ADMIN_USER
            value: grc-service-account@cabinetoffice.gov.uk
          - name: NOTIFY_API
            value: <NOTIFYAPI>
          - name: NOTIFY_OVERRIDE_EMAIL
            value: ivan.touloumbadjian@hmcts.net
          - name: BUCKET_NAME
            value: <BUCKETNAME>
          - name: AWS_ACCESS_KEY_ID
            value: <AWSACCESSKEY>
          - name: AWS_SECRET_ACCESS_KEY
            value: <AWSSECRETACCESSKEY>
          - name: AWS_REGION
            value: eu-west-2
          - name: GOVUK_PAY_API
            value: "https://publicapi.payments.service.gov.uk/"
          - name: GOVUK_PAY_API_KEY
            value: <GOVUK_PAY_API_KEY>