apiVersion: apps/v1
kind: Deployment
metadata:
  name: grc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grc-app
  template:
    metadata:
      labels:
        app: grc-app
    spec:
      containers:
      - name: grc-app
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/pet/grc-preprod-ecr:grc-app-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: dps-rds-instance-output
                key: url
          - name: CONTENT_API_URL
            value: "http://content-api-service:4567/image_url.json"
          - name: FLASK_APP
            value: grc
          - name: SQLALCHEMY_DATABASE_URI
            value: "postgresql://cpodXL33DA:Jm4fxF4A4DRIJYYo@cloud-platform-5e7c8a16ebe2c21b.cdwm328dlye6.eu-west-2.rds.amazonaws.com:5432/db5e7c8a16ebe2c21b"
          - name: DEFAULT_ADMIN_USER
            value: grc-service-account@cabinetoffice.gov.uk
          - name: NOTIFY_OVERRIDE_EMAIL
            value: ivan.touloumbadjian@hmcts.net
          - name: AWS_REGION
            value: eu-west-2
          - name: GOVUK_PAY_API
            value: "https://publicapi.payments.service.gov.uk/"