apiVersion: apps/v1
kind: Deployment
metadata:
  name: grc-clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grc-clamav
  template:
    metadata:
      labels:
        app: grc-clamav
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: grc-clamav
        image: quay.io/ukhomeofficedigital/clamav:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3310