apiVersion: v1
kind: Service
metadata:
  name: grc-clamav-service
  labels:
    app: grc-clamav-service
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 3310
  selector:
    app: grc-clamav