apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gender-recognition-service
  namespace: grc-preprod
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: gender-recognition-service-grc-preprod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
#     5.151.166.193/32, 94.192.178.93/32, 52.167.144.219 belong to David Scott (david.scott@wearegroup.com) who is testing in preprod
    nginx.ingress.kubernetes.io/whitelist-source-range: >-
      194.33.196.0/24,
      194.33.192.0/24,
      51.149.249.0/29,
      51.149.249.32/29,
      51.149.250.0/24,
      81.153.123.31/32,
      90.209.17.46/32,
      5.151.166.193/32,
      94.192.178.93/32,
      52.167.144.219,
      90.209.73.29/32,
      128.77.75.64/26,
      86.145.190.211,
      86.135.149.138,
      109.224.139.207
    nginx.ingress.kubernetes.io/server-snippet: |
      location @custom_403 {
        return 403 "{\"msg\":\"<br/>Gender Recognition Panel<br/>This is a restricted page. Please contact by email or telephone if you need access<br/>GRPenquiries@justice.gov.uk<br>Telephone: 0300 123 4503  Monday to Friday, 9am to 5pm<br/>\"}";
      }
      error_page 403 @custom_403;
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=pet"

      SecRequestBodyLimit 78643200

      SecRule REQUEST_URI "@beginsWith /upload" \
        "id:1000,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveById=951240"
      
      # Disable specific ModSecurity rules related to file size for upload path
      SecRule REQUEST_URI "@beginsWith /upload" \
        "id:1001,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveById=920420"

spec:
  ingressClassName: modsec
  tls:
  - hosts:
    - preprod.gender-recognition.service.justice.gov.uk
    secretName: gender-recognition-service-app-secret

  rules:
  - host: preprod.gender-recognition.service.justice.gov.uk
    http:
      paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: maintenance-page-svc
                port:
                  number: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gender-recognition-service-smoketest
  namespace: grc-preprod
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: gender-recognition-service-grc-preprod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: 88.97.207.18/32

spec:
    ingressClassName: modsec
    tls:
      - hosts:
          - preprod.gender-recognition.service.justice.gov.uk
        secretName: gender-recognition-service-app-secret

    rules:
      - host: preprod.gender-recognition.service.justice.gov.uk
        http:
          paths:
            - path: /smoketest
              pathType: ImplementationSpecific
              backend:
                service:
                  name: grc-app-service
                  port:
                    number: 3000