apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gender-recognition-service
  namespace: grc-preprod
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    external-dns.alpha.kubernetes.io/set-identifier: gender-recognition-service-grc-preprod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
  - hosts:
    - gender-recognition-service-preprod.apps.live.cloud-platform.service.justice.gov.uk
  rules:
  - host: gender-recognition-service-preprod.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: grc-app-service
                port: 
                  number: 3000
