name: 'Deploy (production)'

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-shared.yml
    with:
      cf_space: 'production'
      app_name_public: 'grc-production'
      app_name_admin: 'grc-production-admin'
      manifest_name: 'prod'
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
