name: 'Deploy (sandbox)'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-shared.yml
    with:
      cf_space: 'sandbox'
      app_name_public: 'geo-gender-recognition-certificate'
      app_name_admin: 'geo-gender-recognition-certificate-admin'
      manifest_name: 'sandbox'
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
