name: 'Deploy (staging)'

on:
  push:
    tags:
      - 'stage-*'

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-shared.yml
    with:
      cf_space: 'staging'
      app_name_public: 'grc-staging'
      app_name_admin: 'grc-staging-admin'
      manifest_name: 'staging'
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
